feat(config): add new resources, permissions and dependencies
UnoHouse/UnoHouseAndroid pull request #1
Opened 2017-04-11 10:50 UTC by S-ido

2017-04-11 15:11 UTC, RafalSalwa commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_CONTACTS" />
Po co nam te uprawnienia?

2017-04-11 15:11 UTC, RafalSalwa commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_PROFILE" />
Po co nam te uprawnienia?

2017-04-11 15:13 UTC, S-ido commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_PROFILE" />
A te już nie potrzebne, były do autouzupełniania maila, ale wywaliłem.

2017-04-11 15:14 UTC, RafalSalwa commented on app/src/main/res/values/strings.xml
> +    <string name="permission_rationale">"Contacts permissions are needed for providing email
Po tym wierszu wnioskuję że możliwe będzie auto uzupełnianie maila z książki telefonicznej, Tak?
Czy zapewni nam to mozliwosć zapamiętywania sesji? czyli bycie cały czas zalogowanym, korzystajac z naszego konta?
Czy w takim wypadku nie powinniśmy rozważyć też rejestracji?

2017-04-11 15:14 UTC, S-ido commented on app/src/main/res/values/strings.xml
> +    <string name="permission_rationale">"Contacts permissions are needed for providing email
Podpowiadania maila już nie ma. Tak czy siak nie ma to nic wspólnego z sesją.

2017-04-11 15:15 UTC, S-ido commented on app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.READ_CONTACTS" />
Już nie potrzebne, były do autouzupełniania maila, ale wywaliłem.

2017-04-11 15:16 UTC, RafalSalwa requested changes
@S-ido ogólnie ok. brakuje tylko .gitignore oraz reguły ignore na fodler .idea/ 
Nie potrzebujemy wiązać projektu z Jednym IDE, oraz narzucania settingsów. Niech każdy sobie wybierzez z czego chce korzystać ;)

2017-04-21 12:05 UTC, RafalSalwa commented on app/src/main/java/pl/com/salwa/unohouse/unohouseandroid/activities/LoginActivity.java
> +//        }
@S-ido wywalić.

2017-04-21 12:06 UTC, RafalSalwa commented on app/src/main/java/pl/com/salwa/unohouse/unohouseandroid/activities/LoginActivity.java
> +        // Check for a valid password, if the user entered one.
@S-ido wywalić komentarze.

2017-04-21 12:32 UTC, closed without merging